### ISSUE TITLE
Unable to use header feature

### ISSUE THREAD

**Issue by RussellHaley** [geoffleyland/lua-csv#5]
Hello! I've just started using your tool. As follows:
--split-test.lua
```
package.path = package.path..";/home/russellh/Git/lua-csv/lua/?.lua"
local csv = require("csv")

local f = csv.open(arg[1],{header=true})
for fields in f:lines() do
  for i, v in ipairs(fields) do print(i, v) end
end
```

--run as lua53 and lua52
`lua52 split-test.lua /home/russellh/Git/lua-csv/test-data/header.csv `

The above command gives me no results. Can you tell me what I am doing wrong?
Thanks!

**Comment by geoffleyland** [comment]
If you say the file has headers, then you're handed back a table with the header titles as keys and the line values as values.  You need to use pairs, not ipairs.

**Comment by RussellHaley** [comment]
Of course. Thanks so much!
